[package]
name = "journal"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
eframe = "0.33.3"
egui = "0.33.3"
rfd = "0.17.2"
serde = {version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_with = "3.16.1"
